# -*- coding: utf-8 -*-
"""WGCNA after ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YdXkAAM4JGPmSPiHQQ2EptocKNsm3cdX

## Mount Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""## Import Libraries"""

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import shap  # SHAP for model interpretability

# ML libraries
from sklearn.model_selection import train_test_split  # split dataset into train/test
from sklearn.preprocessing import LabelEncoder, StandardScaler  # LabelEncoder: text -> numeric labels | StandardScaler: feature scaling
from sklearn.ensemble import RandomForestClassifier  # Random Forest classifier
from sklearn.svm import SVC  # Support Vector Machine classifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score  # model evaluation metrics
from xgboost import XGBClassifier  # XGBoost classifier
from collections import Counter  # used later for the stability check

"""## Load Dataset"""

df_gene_module = pd.read_csv("/content/drive/My Drive/Latihan WGCNA/metabric_gene_modules_R.csv")
df_gene_module.shape

df = pd.read_csv("/content/drive/My Drive/Latihan WGCNA/METABRIC_RNA_Mutation.csv")
df.shape

"""## Identify Columns"""

# mutation columns
cols_mutation = [c for c in df.columns if c.lower().endswith("_mut")]

# clinical info columns
cols_clinical_all = [
    "patient_id", "age_at_diagnosis", "type_of_breast_surgery",
    "cancer_type", "cancer_type_detailed", "cellularity", "chemotherapy",
    "pam50_+_claudin-low_subtype", "cohort", "er_status_measured_by_ihc",
    "er_status", "neoplasm_histologic_grade", "her2_status_measured_by_snp6",
    "her2_status", "tumor_other_histologic_subtype", "hormone_therapy",
    "inferred_menopausal_state", "integrative_cluster",
    "primary_tumor_laterality", "lymph_nodes_examined_positive",
    "mutation_count", "nottingham_prognostic_index", "oncotree_code",
    "overall_survival_months", "overall_survival", "pr_status",
    "radio_therapy", "3-gene_classifier_subtype", "tumor_size",
    "tumor_stage", "death_from_cancer",
]
cols_clinical_all = [c for c in cols_clinical_all if c in df.columns]

# check for numeric dtype
is_numeric_col = df.dtypes.apply(lambda t: pd.api.types.is_numeric_dtype(t))

# gene columns = numeric columns that are neither clinical nor mutation columns
cols_gene_all = [
    c for c in df.columns
    if c not in cols_clinical_all and c not in cols_mutation and is_numeric_col[c]
]

# patient ID column
id_col = "patient_id" if "patient_id" in df.columns else df.columns[0]

# cancer subtype column
pam50_col = "pam50_+_claudin-low_subtype"

print(f"Total gen tersedia: {len(cols_gene_all)}")

# --- Column check: confirm the raw column names actually present in df ---
print("Total kolom di df:", len(df.columns))
print("Contoh kolom (50 pertama):", list(df.columns)[:50])

"""## Select Significant Module Genes"""

# modules identified in the previous WGCNA run
modul_signifikan = ["blue", "turquoise", "brown", "yellow"]

all_module_genes = df_gene_module.loc[
    df_gene_module["module"].isin(modul_signifikan), "gene"
].tolist()

# keep only gene names that actually exist in the raw dataframe (case-sensitive check)
chosen_gene = [gen for gen in all_module_genes if gen in df.columns]
unmatched_genes = [gen for gen in all_module_genes if gen not in df.columns]

print(f"Jumlah gen dari modul signifikan: {len(chosen_gene)}")
print("Contoh gen:", chosen_gene[:10])

# --- Gene name matching check ---
print("Jumlah gen di modul signifikan (sebelum filter):", len(all_module_genes))
print("Jumlah gen yang match ke df.columns:", len(chosen_gene))
print("Jumlah gen yang TIDAK match:", len(unmatched_genes))
print("Contoh gen yang tidak match:", unmatched_genes[:10])

# check whether unmatched names are just a case-sensitivity issue
df_cols_lower = {c.lower(): c for c in df.columns}
recovered_by_lowercase = [g for g in unmatched_genes if g.lower() in df_cols_lower]
print("Jumlah gen yang match kalau case-insensitive:", len(recovered_by_lowercase))
print("Contoh:", recovered_by_lowercase[:10])

"""## Additional Clinical Traits"""

trait_klinis_target = [
    "age_at_diagnosis",
    "tumor_size",
    "tumor_stage",
    "lymph_nodes_examined_positive",
    "nottingham_prognostic_index",
]

trait_klinis_dipakai = [clinic for clinic in trait_klinis_target if clinic in df.columns]
unmatched_traits = [clinic for clinic in trait_klinis_target if clinic not in df.columns]

print(f"Jumlah trait klinis yang digunakan: {len(trait_klinis_dipakai)}")
print("Trait klinis yang digunakan:", trait_klinis_dipakai)

# --- Clinical trait matching check ---
print("Trait klinis target:", trait_klinis_target)
print("Trait klinis yang match:", trait_klinis_dipakai)
print("Trait klinis yang TIDAK match:", unmatched_traits)

recovered_traits = [c for c in unmatched_traits if c.lower() in df_cols_lower]
print("Trait yang match kalau case-insensitive:", recovered_traits)

"""## Filter to the 5 PAM50 Classes"""

kelas_pam50 = ["Basal", "LumA", "LumB", "Her2", "Normal"]

df_ml = df[df[pam50_col].isin(kelas_pam50)].copy()
print(f'Distribusi kelas setelah filter: {df_ml[pam50_col].value_counts()}')

# drop rows with missing values in the columns actually used
kolom_dipakai = chosen_gene + trait_klinis_dipakai
df_ml = df_ml.dropna(subset=kolom_dipakai + [pam50_col])
print("Jumlah sampel setelah buang NA:", df_ml.shape[0])

"""## Define X (Features) and Y (Label)"""

# X values
X = df_ml[kolom_dipakai].apply(pd.to_numeric, errors="coerce")
X = X.fillna(X.median(numeric_only=True))

# Y values
le = LabelEncoder()
y = le.fit_transform(df_ml[pam50_col])
print("Kelas:", dict(zip(le.classes_, range(len(le.classes_)))))

# --- Final feature set check: confirm nothing was silently dropped ---
print("\n=== RINGKASAN FITUR AKHIR ===")
print("Jumlah gen dipakai (chosen_gene):", len(chosen_gene))
print("Jumlah trait klinis dipakai (trait_klinis_dipakai):", len(trait_klinis_dipakai))
print("Total fitur X:", X.shape[1])
print("Daftar fitur X:", list(X.columns))

# train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print("Train:", X_train.shape, "| Test:", X_test.shape)

# scaling, needed for SVM
# scaling matters for SVM; it is harmless to also apply it to the tree models
scaler = StandardScaler()
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train), columns=X.columns, index=X_train.index)
X_test_scaled = pd.DataFrame(scaler.transform(X_test), columns=X.columns, index=X_test.index)

"""## XGBoost"""

xgb_model = XGBClassifier(
    objective="multi:softprob",
    num_class=len(le.classes_),
    eval_metric="mlogloss",
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    random_state=42,
    n_jobs=-1,
)

xgb_model.fit(X_train, y_train)  # tree-based model, no scaling needed
y_pred_xgb = xgb_model.predict(X_test)

print("=== XGBoost ===")
print("Akurasi:", accuracy_score(y_test, y_pred_xgb))
print(classification_report(y_test, y_pred_xgb, target_names=le.classes_))

"""## Random Forest (RF)"""

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=42,
    n_jobs=-1,
)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("=== Random Forest ===")
print("Akurasi:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf, target_names=le.classes_))

"""## SVM"""

svm_model = SVC(
    kernel="rbf",
    C=1.0,
    gamma="scale",
    probability=True,  # required so SHAP KernelExplainer can be used later
    random_state=42,
)
svm_model.fit(X_train_scaled, y_train)
y_pred_svm = svm_model.predict(X_test_scaled)

print("=== SVM ===")
print("Akurasi:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm, target_names=le.classes_))

"""## Accuracy Comparison"""

hasil_akurasi = pd.DataFrame({
    "model": ["XGBoost", "Random Forest", "SVM"],
    "accuracy": [
        accuracy_score(y_test, y_pred_xgb),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_svm),
    ]
})
print(hasil_akurasi)

plt.figure(figsize=(6, 4))
plt.bar(hasil_akurasi["model"], hasil_akurasi["accuracy"], color=["#1f77b4", "#2ca02c", "#d62728"])
plt.ylabel("Accuracy")
plt.title("Perbandingan akurasi model (PAM50 subtype)")
plt.ylim(0, 1)
plt.savefig("/content/drive/My Drive/Latihan WGCNA/gambar alur 1/perbandingan_akurasi_model.png", dpi=150, bbox_inches="tight")
plt.show()

"""## SHAP for XGBoost"""

explainer_xgb = shap.TreeExplainer(xgb_model)
shap_values_xgb = explainer_xgb.shap_values(X_test)

# --- SHAP array shape check (XGBoost) ---
# Expected shape: (n_samples, n_features, n_classes). If this 3D array is passed
# to summary_plot without slicing a specific class, some shap versions misread
# it as interaction values (n_samples, n_features, n_features) instead of
# per-class SHAP values -- comparing n_features vs n_classes below confirms which.
print("\n=== CEK SHAPE SHAP VALUES (XGBoost) ===")
print("Tipe shap_values_xgb:", type(shap_values_xgb))
if hasattr(shap_values_xgb, "shape"):
    print("Shape shap_values_xgb:", shap_values_xgb.shape)
    print("Shape X_test:", X_test.shape)
    print("Jumlah kelas (le.classes_):", len(le.classes_))
elif isinstance(shap_values_xgb, list):
    print("shap_values_xgb berupa list, panjang:", len(shap_values_xgb))
    print("Shape tiap elemen:", [arr.shape for arr in shap_values_xgb])

plt.figure()
shap.summary_plot(shap_values_xgb, X_test, class_names=le.classes_, show=False)
plt.savefig("/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_summary_xgboost.png", dpi=150, bbox_inches="tight")
plt.show()

shap.summary_plot(shap_values_xgb, X_test, class_names=le.classes_,
                   plot_type="bar", show=False)
plt.savefig("/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_bar_xgboost.png", dpi=150, bbox_inches="tight")
plt.show()

"""## SHAP for Random Forest"""

explainer_rf = shap.TreeExplainer(rf_model)
shap_values_rf = explainer_rf.shap_values(X_test)

# --- SHAP array shape check (Random Forest) ---
print("\n=== CEK SHAPE SHAP VALUES (Random Forest) ===")
print("Tipe shap_values_rf:", type(shap_values_rf))
if hasattr(shap_values_rf, "shape"):
    print("Shape shap_values_rf:", shap_values_rf.shape)
elif isinstance(shap_values_rf, list):
    print("shap_values_rf berupa list, panjang:", len(shap_values_rf))
    print("Shape tiap elemen:", [arr.shape for arr in shap_values_rf])

plt.figure()
shap.summary_plot(shap_values_rf, X_test, class_names=le.classes_, show=False)
plt.savefig("/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_summary_rf.png", dpi=150, bbox_inches="tight")
plt.show()

shap.summary_plot(shap_values_rf, X_test, class_names=le.classes_,
                   plot_type="bar", show=False)
plt.savefig("/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_bar_rf.png", dpi=150, bbox_inches="tight")
plt.show()

"""## SHAP for SVM"""

background = shap.sample(X_train_scaled, 50, random_state=42)  # reference/background data
X_test_small = X_test_scaled.sample(min(20, len(X_test_scaled)), random_state=42)

explainer_svm = shap.KernelExplainer(svm_model.predict_proba, background)
shap_values_svm = explainer_svm.shap_values(X_test_small, nsamples=100)

plt.figure()
shap.summary_plot(shap_values_svm, X_test_small, class_names=le.classes_, show=False)
plt.savefig("/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_summary_svm.png", dpi=150, bbox_inches="tight")
plt.show()

shap.summary_plot(shap_values_svm, X_test_small, class_names=le.classes_,
                   plot_type="bar", show=False)
plt.savefig("/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_bar_svm.png", dpi=150, bbox_inches="tight")
plt.show()

"""## Per-Class + Cross-Model SHAP Ranking (Biomarker Screening)"""

CLASS_OF_INTEREST = "Basal"  # change this to screen a different PAM50 subtype

def per_class_mean_abs_shap(shap_values, feature_names, class_names):
    """
    Accepts shap_values either as a 3D array (n_samples, n_features, n_classes)
    OR as a list per class (older shap versions), and returns a DataFrame
    (features x classes) of mean(|SHAP value|).
    """
    if isinstance(shap_values, list):
        arr = np.stack(shap_values, axis=-1)  # -> (n_samples, n_features, n_classes)
    else:
        arr = shap_values
    mean_abs = np.abs(arr).mean(axis=0)  # (n_features, n_classes)
    return pd.DataFrame(mean_abs, index=feature_names, columns=class_names)

imp_xgb = per_class_mean_abs_shap(shap_values_xgb, X_test.columns, le.classes_)
imp_rf = per_class_mean_abs_shap(shap_values_rf, X_test.columns, le.classes_)
imp_svm = per_class_mean_abs_shap(shap_values_svm, X_test_small.columns, le.classes_)

print(f"\n=== TOP 10 FITUR UNTUK KELAS: {CLASS_OF_INTEREST} (per model) ===")
print("\nXGBoost:")
print(imp_xgb[CLASS_OF_INTEREST].sort_values(ascending=False).head(10))
print("\nRandom Forest:")
print(imp_rf[CLASS_OF_INTEREST].sort_values(ascending=False).head(10))
print("\nSVM:")
print(imp_svm[CLASS_OF_INTEREST].sort_values(ascending=False).head(10))

# --- Cross-model rank agreement ---
# Rank is used instead of the raw SHAP value so XGBoost, Random Forest, and SVM
# can be compared fairly, since their SHAP values are not on the same numeric
# scale (TreeExplainer vs KernelExplainer). A feature with a low average rank
# (close to 1) is consistently important across all three models -- a more
# credible candidate than one with a single high score in only one model.
rank_table = pd.DataFrame({
    "xgb_rank": imp_xgb[CLASS_OF_INTEREST].rank(ascending=False),
    "rf_rank": imp_rf[CLASS_OF_INTEREST].rank(ascending=False),
    "svm_rank": imp_svm[CLASS_OF_INTEREST].rank(ascending=False),
})
rank_table["avg_rank"] = rank_table.mean(axis=1)
rank_table = rank_table.sort_values("avg_rank")

print(f"\n=== KANDIDAT BIOMARKER UNTUK KELAS: {CLASS_OF_INTEREST} (Konsisten di 3 Model) ===")
print(rank_table.head(10))

rank_table.to_csv(f"/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_rank_agreement_{CLASS_OF_INTEREST}.csv")

"""## Directional Check + Stability Check"""

TOP_CANDIDATES = rank_table.head(4).index.tolist()  # e.g. ['egfr', 'map2', 'gata3', 'e2f3']
CLASS_INDEX = list(le.classes_).index(CLASS_OF_INTEREST)

# --- 1. Directional check (beeswarm plot for one class, top candidates only) ---
# A normal beeswarm plot (not the bar version) for a single class: slice
# shap_values_xgb[:, :, CLASS_INDEX], then filter X_test down to TOP_CANDIDATES
# so the plot stays focused instead of showing every feature.

X_test_focus = X_test[TOP_CANDIDATES]
shap_values_xgb_focus = shap_values_xgb[:, :, CLASS_INDEX]
col_idx = [list(X_test.columns).index(g) for g in TOP_CANDIDATES]
shap_values_xgb_focus = shap_values_xgb_focus[:, col_idx]

plt.figure()
shap.summary_plot(shap_values_xgb_focus, X_test_focus, show=False)
plt.title(f"Directional check (XGBoost) - kelas: {CLASS_OF_INTEREST}")
plt.savefig(f"/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_directional_xgb_{CLASS_OF_INTEREST}.png", dpi=150, bbox_inches="tight")
plt.show()

# How to read it: red dots (high feature value) clustering on the positive side
# means high expression pushes the prediction toward this class; blue dots
# (low value) clustering on the negative side means the opposite. If red and
# blue overlap near zero with no separation, the direction is inconsistent and
# the candidate is weaker even if its overall SHAP importance score is high.

# --- 2. Stability check (repeat the split several times, check whether the
#     same top-10 genes keep showing up) ---
# This repeats the single train-test split with different random seeds and
# tracks whether the same genes stay in the top 10 for the class of interest
# across all repeats. A gene that only appears in one split's top 10 may just
# be an artifact of that particular split rather than a robust signal.

N_REPEATS = 5
top_n_appearances = Counter()

for seed in range(N_REPEATS):
    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=0.2, random_state=seed, stratify=y
    )
    model_check = XGBClassifier(
        objective="multi:softprob",
        num_class=len(le.classes_),
        eval_metric="mlogloss",
        n_estimators=300,
        max_depth=4,
        learning_rate=0.05,
        random_state=seed,
        n_jobs=-1,
    )
    model_check.fit(X_tr, y_tr)

    explainer_check = shap.TreeExplainer(model_check)
    shap_values_check = explainer_check.shap_values(X_te)  # (n_samples, n_features, n_classes)

    imp_check = per_class_mean_abs_shap(shap_values_check, X_te.columns, le.classes_)
    top10_this_run = imp_check[CLASS_OF_INTEREST].sort_values(ascending=False).head(10).index.tolist()

    top_n_appearances.update(top10_this_run)

    # NOTE (bug fix): this print used to sit outside the for-loop, so only the
    # last seed's result was ever shown even though the counter above was
    # correctly accumulating all N_REPEATS runs. Moving it here prints every
    # seed's result as the loop runs.
    print(f"Seed {seed} - top 10 untuk {CLASS_OF_INTEREST}:", top10_this_run)

print(f"\n=== STABILITY CHECK: frekuensi muncul di top-10 dari {N_REPEATS} split (kelas: {CLASS_OF_INTEREST}) ===")
stability_table = pd.Series(top_n_appearances).sort_values(ascending=False)
print(stability_table)
stability_table.to_csv(f"/content/drive/My Drive/Latihan WGCNA/gambar alur 1/shap_stability_{CLASS_OF_INTEREST}.csv")
